### ISSUE TITLE
Some windows are not displayed after reloading i3

### ISSUE THREAD

**Issue by link1375** [tryone144/compton#11]
Hi,

I was not sure if I should post this issue here or at the compton-git repo. I am using arch with i3 and wanted to apply blur in combination with transparency. Everything works fine, but if I reload i3 (mod+Shift+r) windows are not properly displayed anymore. The same occurs with the normal compton package. To test if this a general problem for my configuration I installed xcompmgr and there is no problem. Also compton outputs a lot of Bad Window erros. After killing the compton process all windows are displayed but obviously without transparency. Starting the process again leads to the same problem.
I could not determine which applications are affected since e.g. firefox is displayed on one workspace but not on another.

![photo_2019-05-01_20-08-43](https://user-images.githubusercontent.com/33375235/57033340-f4afff80-6c4c-11e9-9cfa-a3022a3f81bb.jpg)
![photo_2019-05-01_20-08-51](https://user-images.githubusercontent.com/33375235/57033452-4062a900-6c4d-11e9-85c8-b5dcde34343b.jpg)

**Comment by tryone144** [comment]
Yeah, I've had the same problem for some time.
I suspected [this line](https://github.com/tryone144/dotfiles/blob/63a08df09b92b39b4113ee97daba1e9887648bcc/compton/.config/compton.conf#L69) in my config to somehow interfere with window mapping.

Killing compton, reloading i3, restarting compton works fine for me.
Have you tested this with https://github.com/yshui/compton as well (the arch linux package is based on this fork)?

**Comment by link1375** [comment]
I tested the offical arch package as well as the aur packages. Unfortunately the problem occur for all of them. Disabling `"0:_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",`  and your suggestion to kill and restarting compton did not work either. 

I guess for now I have to keep xcompmgr running and resign blur.

**Comment by tryone144** [comment]
Killing compton before reloading i3 only works for me if the above problem hasn't already occured. It doesn't work to recover the already "invisible" windows.

I would suggest opening a new issue over at https://github.com/yshui/compton as that fork is actively maintained and this fork's blur shader will eventually be merged into that fork as well.

**Comment by link1375** [comment]
Ok, thank you. Should I close this issue here then?

**Comment by tryone144** [comment]
This issue has been resolved in https://github.com/yshui/picom/issues/134.
A fix has already been merged into the `next` branch upstream.
