### ISSUE TITLE
Config option for kawase blur?

### ISSUE THREAD

**Issue by GOKOP** [tryone144/compton#12]
Is there a way of specifying that I want to use kawase blur in compton.conf?
Currently I'm using command options but that's not very convenient.

**Comment by tryone144** [comment]
This should do the trick: https://github.com/tryone144/compton/blob/241bbc50285e58cbc6a25d45066689eeea913880/compton.sample.conf#L35

Alternatively with the newer [improved_fbo](https://github.com/tryone144/compton/tree/improved_fbo) branch: https://github.com/tryone144/compton/blob/a770a4543058620999d5f259cd190cfb98763e6c/compton.sample.conf#L35

**Comment by GOKOP** [comment]
Works, thanks!
