### ISSUE TITLE
Picture in terminal

### ISSUE THREAD

**Issue by Delayless** [tryone144/compton#20]
Hello  @tryone144 , the compositor is so great.but I found It have a bug for display picture in terminal.
I tried other terminal, but it still doesn't work unless I run "killall compton". So I think it might be a compton's bug.
My configuration is the default file from your respository.
I'm sorry for my English expression to you :rofl: 。

**Comment by tryone144** [comment]
What exactly are you trying to achieve? What terminal emulator are you using?
Maybe you can post an image of how it looks and how you expect it to look like.

**Comment by Delayless** [comment]
OS:Ubuntu 16.04
Terminal : alacritty, xfce4-terminal
![2019-12-09-031816_1366x768_scrot](https://user-images.githubusercontent.com/42591058/70555823-c4551a00-1bba-11ea-9c2b-33613b7363f3.png)
Thanks for your reply. Actually, I reinstalled an new operating system----Manjaro today. On my new system, The Compton is perfect by the same configuration file.Thank you again. If you know why this happens on the Ubuntu 16.04, please reply below for the convenience of those who have the same situation. If no, please delete the issue, sorry to disturb you.
