### ISSUE TITLE
Config file location

### ISSUE THREAD

**Issue by furanzoni** [tryone144/compton#21]
Where is the configuration file location? On `~/.config/compton `there's nothing (more like the folder doesn't even exist).

**Comment by tryone144** [comment]
As documented in the [Manpage](https://github.com/tryone144/compton/blob/dual_kawase/man/compton.1.asciidoc#configuration-files), compton looks for the following files in that order and uses the first it finds:
- `~/.config/compton.conf`
- `~/.compton.conf`
- `/etc/xdg/compton.conf`

These won't exist when you install compton for the first time. If `~/.config/compton.conf` does not exist, you can just copy the [sample config](https://github.com/tryone144/compton/blob/dual_kawase/compton.sample.conf) to that location and modify it.

**Comment by furanzoni** [comment]
Thank you very much.
