### ISSUE TITLE
Blur kawase not working

### ISSUE THREAD

**Issue by furanzoni** [tryone144/compton#22]
**Platform**: Manjaro + i3-gaps
**Compton version**: git-v0.1_beta2-95-g241bbc5-2018-02-22
**Compton configuration**: https://pastebin.com/5PnZsXCQ
**Terminal**: Termite
I've no idea why it doesn't work.

**Comment by tryone144** [comment]
Does your termite config specify a transparent background, i.e. like [this](https://github.com/tryone144/dotfiles/blob/8de50cb39b4688f2bc9b891255fe2d9a6df6cb73/termite/.config/termite/config#L40)?

The blur-strength of 20 is rather extreme and might produce nearly single-colored backgrounds on smaller resolutions. You may want to try with smaller levels like 5 or 7 first.

**Comment by furanzoni** [comment]
> Does your termite config specify a transparent background, i.e. like [this](https://github.com/tryone144/dotfiles/blob/8de50cb39b4688f2bc9b891255fe2d9a6df6cb73/termite/.config/termite/config#L40)?
> 
> The blur-strength of 20 is rather extreme and might produce nearly single-colored backgrounds on smaller resolutions. You may want to try with smaller levels like 5 or 7 first.

I didn't, now I uncommented the specific line for the transparent background but there's no difference whatsoever. Like, between using compton normally and using kawasa blur there's no difference, not even changing the blur's strength will do nothing.

**Comment by tryone144** [comment]
Could you post a screenshot, i.e. via imgur? And the output of compton itself?

**Comment by furanzoni** [comment]
Nvm, a reboot solved it. Now it is working fine. Really sorry to have wasted your time again.
