### ISSUE TITLE
"unrecognized option '--blur-strength'"

### ISSUE THREAD

**Issue by vegerot** [tryone144/compton#24]
Platform: Example: Rasbian Buster arm64

GPU, drivers, and screen setup: Raspberry Pi 

Compton version: vgit-f92eb

Compton configuration: Irrelevent since I'm running from commandline, but [here](https://github.com/vegerot/dotfiles/blob/pi/.config/compton.conf) it is anyways
### Steps of reproduction
```
/usr/local/bin/compton  --experimental-backends --backend glx --blur-method dual_kawase --blur-strength 12
```

### Expected behavior

I expected the background to be blurred like how the `master` branch is when using `blur-strength=12` and `blur-method=kawase`.  But hopefully with better performance, given how badly my Raspberry Pi 4b chokes

**Comment by tryone144** [comment]
See https://github.com/yshui/picom/pull/286
Once this is merged, I can add said options.

**Comment by tryone144** [comment]
https://github.com/yshui/picom/pull/286 has been merged upstream. `feature/dual_kawase` finally supports the command line options mentioned in the README. :tada:
