### ISSUE TITLE
Edges preserving

### ISSUE THREAD

**Issue by anstadnik** [tryone144/compton#25]
Platform:  Arch linux

GPU, drivers, and screen setup:  Intel UHD Graphics 620, mesa 19.3.1-1, laptop screen and monitors configured side-by-side with xrandr (works the same with laptop screen only) 

Compton version:  bgit-f92eb from aur [repo](https://aur.archlinux.org/packages/picom-tryone-git/)

Compton configuration:  Written below

### Steps of reproduction

Install picom from the aur repo, use dual_kawase blur method 

### Expected behavior

 For some reason I can clearly see the edges of objects. I think that that should not be the case with blurring. Is that a bug or intended behavior?

### Current Behavior & Other details

![DeepinScreenshot_select-area_20200106110219](https://user-images.githubusercontent.com/40110937/71808184-c7d2a880-3075-11ea-9597-53b318f5aba4.png)
```blur:
{
  method = "dual_kawase";
  strength = 20;
};
```

![DeepinScreenshot_select-area_20200106110439](https://user-images.githubusercontent.com/40110937/71808185-c7d2a880-3075-11ea-8db7-c3e1e7f85d8d.png)

```blur:
{
  method = "dual_kawase";
  strength = 1;
};
```

![DeepinScreenshot_select-area_20200106111247](https://user-images.githubusercontent.com/40110937/71808186-c86b3f00-3075-11ea-83a5-4bed42297b5a.png)

```blur:
{
  method = "box";
  size = 20;
  deviation = 20.0;
};
```

**Comment by tryone144** [comment]
How do you achieve the transparency effect? Is it by setting it with `active-opacity` or an `opacity-rule`? And have you set `blur-background-fixed = true`? If not, the blur is applied with some alpha-value to compensate for windows fading out with `inactive-opacity = 0` (see #2). This feature might need some work though as I am not sure the current implementation aligns with the way the new backends are intended to work.

**Comment by anstadnik** [comment]
I used `opacity-rule` with `inactive-opacity = 1; active-opacity = 1;`, and the setting `blur-background-fixed = true` solved the issue, now blur works perfectly, thank you.
