### ISSUE TITLE
Remove Darkening Around Kawase'd Windows

### ISSUE THREAD

**Issue by ghost** [tryone144/compton#26]
### Platform

Arch Linux

### GPU, drivers, and screen setup

Intel Graphics, xf86-video-intel
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) Ivybridge Mobile  (0x166)
    Version: 19.3.2
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.2
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 4.2 (Core Profile) Mesa 19.3.2
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 19.3.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 19.3.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```

### Environment

Awesome Window Manager

### picom version

```
picom feature/dual_kawase vgit-f92eb
```

### Configuration:
```
# Shadow
shadow = false;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
log-level = "warn";
# log-file = "/path/to/your/log/file";
shadow-opacity = 0.0;
# shadow-red = 0.0;
# shadow-green = 0.0;
# shadow-blue = 0.0;
shadow-exclude = [
	"name = 'Notification'",
	"class_g = 'Conky'",
	"class_g ?= 'Notify-osd'",
	"class_g = 'Cairo-clock'",
	"_GTK_FRAME_EXTENTS@:c"
];
# shadow-exclude = "n:e:Notification";
# shadow-exclude-reg = "x10+0+0";
# xinerama-shadow-crop = true;

# Opacity
# inactive-opacity = 0.8;
# active-opacity = 0.8;
# frame-opacity = 0.7;
# inactive-opacity-override = false;
# inactive-dim = 0.2;
# inactive-dim-fixed = true;

blur: {
  method = "dual_kawase";
  strength = 2.0;
  # deviation = 1.0;
  # kernel = "11x11gaussian";
}

# blur-background = true;
# blur-background-frame = true;
blur-kern = "3x3box";
# blur-kern = "5,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1";
# blur-background-fixed = true;
blur-background-exclude = [
	"window_type = 'dock'",
	"window_type = 'desktop'",
	"_GTK_FRAME_EXTENTS@:c"
];
# opacity-rule = [ "80:class_g = 'URxvt'" ];

# max-brightness = 0.66

# Fading
fading = true;
# fade-delta = 30;
fade-in-step = 0.03;
fade-out-step = 0.03;
# no-fading-openclose = true;
# no-fading-destroyed-argb = true;
fade-exclude = [ ];

# Other
backend = "glx";
mark-wmwin-focused = true;
mark-ovredir-focused = true;
# use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
vsync = true;
# sw-opti = true;
# unredir-if-possible = true;
# unredir-if-possible-delay = 5000;
# unredir-if-possible-exclude = [ ];
focus-exclude = [ "class_g = 'Cairo-clock'" ];
detect-transient = true;
detect-client-leader = true;
invert-color-include = [ ];
# resize-damage = 1;

# GLX backend
# glx-no-stencil = true;
# glx-no-rebind-pixmap = true;
# xrender-sync-fence = true;
use-damage = true;

# Window type settings
wintypes:
{
  tooltip = { fade = true; shadow = false; opacity = 0.75; focus = true; full-shadow = false; };
  dock = { shadow = false; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};
```

### Steps of reproduction

1. Enable the blur using the blur:{ .. } just like in my config above.
2. Add opacity effect to terminals.
3. Remove gaps or move two blurred transparent window next to each other

### Expected behavior
There's should be no darkening between the blurred windows 

### Current Behavior
There are some darkening around the blurred terminals

![20200119_195310](https://user-images.githubusercontent.com/56459896/72681995-e3bd5c00-3b03-11ea-8459-5cee65c01c2c.png)

### Other details

If I set the blur method to `none`, the dark borders disappeared. But even setting the blur strength to `0.0`, it still appears.
Earlier, I found out that the shadow-like effect shows when if there is `--experimental-backends`

With that being said, my question is: Is there a way to disable this effect? 
Launching picom by: 
```
picom -b --experimental-backends --dbus --config picom.conf 
```

**Comment by tryone144** [comment]
Hi, this is most likely the same effect you described here: https://github.com/yshui/picom/issues/298

The blur-kernel is applied sequentially for each window and the shadow-like effect is actually the partially blurred borders of the adjacent windows. A few pixels around the real window border are taken into account to prevent some clipping-artificats.

You may try out the experimental `--transparent-clipping` option mentioned here https://github.com/yshui/picom/issues/265#issuecomment-560022797 which disregards all windows and just blurs the wallpaper.

**Comment by ghost** [comment]
Oh, I see. Thanks for the explanation. I posted here again because I thought using the dual_kawase method we can disable that. Thanks again!!

> You may try out the experimental --transparent-clipping option mentioned here yshui#265 (comment) which disregards all windows and just blurs the wallpaper.

Actually I already tried it but the *shadow-like effect* was still there. Anyway, thank you for bringing your kawase method to picom!
