### ISSUE TITLE
"focused" and "!focused" reversed

### ISSUE THREAD

**Issue by BigB00st** [tryone144/compton#28]
Platform: Arch 5.4.14 amd64

Drivers: mesa, xf86-video-intel

WM: i3-gaps

Compton version: vgit-e0149 (picom-tryone latest)

Compton configuration: https://pastebin.com/AaHv0vp5

### Steps of reproduction

In opacity-rule, the programs are considered **focused** when they are **not**, and considered **not focused** when they **are**.
```
opacity-rule = [
  "55:class_g = 'Termite' && focused",
  "85:class_g = 'Termite' && !focused",
  "75:class_g = 'code-oss' && focused",
  "90:class_g = 'code-oss' && !focused"
];
```
Therefore, I gave higher opacity to non focused programs, and lower opacity to focused programs.

### Expected behavior

Focused programs should be focused, and non focused programs shouldn't. When using compton before, I didn't face this problem.

### Current Behavior & Other details

I use --experimental-backend, but the issue exists also without the flag.

**Comment by tryone144** [comment]
See this upsteam issue: https://github.com/yshui/picom/issues/266

Some preliminary testing suggests that the change in https://github.com/yshui/picom/commit/79fc36b3e30989fd638aa0531588e02b564a906c with regard to the `_NET_WM_CLIENT_OPACITY` (see https://github.com/yshui/picom/issues/134 for a discussion why) has introduced a race condition where the updated opacity value is actually one state behind (i.e. `focused` for unfocused windows and `!focused` for focused ones).

I suggest continuing the discussion in the [upstream issue](https://github.com/yshui/picom/issues/266).
