### ISSUE TITLE
Contributing .deb package to apt repository?

### ISSUE THREAD

**Issue by ghost** [tryone144/compton#3]
Heya @tryone144 ! Thanks for sharing your fork of compton - I'm really loving it. I'll admit that it was quite the challenge to find the apt packages containing the deps I needed. So in order to save other Debian/Ubuntu users from the pain that I had to go through, I thought I'd contribute by putting together a nifty .deb package that compiles it easily for them.

Prebuilt binaries might work for other people too, but I'm not totally sure. I guess there's not really much I can ask you, other than for your permission.

**Comment by tryone144** [comment]
Hi,
Bundling the binary in a .deb package is fine with me. There already exists an ArchLinux PKGBUILD somewhere in the AUR, so... :wink:

Keep in mind though, that once https://github.com/yshui/compton/pull/39 is finalized I'll try to merge my changes into that fork as it's actively maintained.

**Comment by ghost** [comment]
Thanks for the tips! It also makes me happy that the future of compton is all well and good because of the open-source community. 👌
