### ISSUE TITLE
Cannot install on ubuntu 19.10

### ISSUE THREAD

**Issue by Bearbobs** [tryone144/compton#32]
meson --buildtype=release . build

The Meson build system
Version: 0.51.2
Source dir: /home/anuj/Desktop/compton
Build dir: /home/anuj/Desktop/compton/build
Build type: native build
Project name: picom
Project version: 7
C compiler for the host machine: cc (gcc 9.2.1 "cc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Has header "stdc-predef.h" : YES 
Compiler for C supports arguments -Wall: YES 
Compiler for C supports arguments -Wcast-function-type: YES 
Compiler for C supports arguments -Wignored-qualifiers: YES 
Compiler for C supports arguments -Wmissing-parameter-type: YES 
Compiler for C supports arguments -Wnonnull: YES 
Compiler for C supports arguments -Wshadow: YES 
Compiler for C supports arguments -Wno-type-limits -Wtype-limits: YES 
Compiler for C supports arguments -Wold-style-declaration: YES 
Compiler for C supports arguments -Woverride-init: YES 
Compiler for C supports arguments -Wsign-compare: YES 
Compiler for C supports arguments -Wtype-limits: YES 
Compiler for C supports arguments -Wuninitialized: YES 
Compiler for C supports arguments -Wshift-negative-value: YES 
Compiler for C supports arguments -Wunused-but-set-parameter: YES 
Compiler for C supports arguments -Wunused-parameter: YES 
Compiler for C supports arguments -Wimplicit-fallthrough: YES 
Compiler for C supports arguments -Wno-unknown-warning-option -Wunknown-warning-option: NO 
Compiler for C supports arguments -Wno-missing-braces -Wmissing-braces: YES 
Compiler for C supports arguments -Wconversion: YES 
Compiler for C supports arguments -Wempty-body: YES 

|Executing subproject test.h method meson 
|
|Project name: test.h
|Project version: undefined
|C compiler for the host machine: cc (gcc 9.2.1 "cc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008")
|Build targets in project: 0
|Subproject test.h finished.

Found pkg-config: /home/linuxbrew/.linuxbrew/bin/pkg-config (0.29.2)
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency libev found: NO (tried pkgconfig and cmake)
Library ev found: YES
Library m found: YES
Run-time dependency x11 found: NO (tried pkgconfig)

src/meson.build:27:1: ERROR: Dependency "x11" not found, tried pkgconfig

A full log can be found at /home/anuj/Desktop/compton/build/meson-logs/meson-log.txt

**Comment by Bearbobs** [comment]
xorg is already installed

**Comment by tryone144** [comment]
You may be missing the respective `*-dev` package for the xserver (should be called `libx11-dev` on debian based systems).

Try installing the [following](https://github.com/yshui/picom#dependencies) (modified) list of development packages:
```console
# apt install libxext-dev libxcb1-dev libxcb-damage0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-randr0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-present-dev libxcb-xinerama0-dev libpixman-1-dev libdbus-1-dev libconfig-dev libgl1-mesa-dev libpcre3-dev libevdev-dev uthash-dev libev-dev libx11-xcb-dev libxdg-basedir-dev
```
With these installed, I could get the current feature/dual_kawase branch to compile under the ubuntu:19.10 docker image.

**Comment by Bearbobs** [comment]
still same issue

**Comment by tryone144** [comment]
The line `Found pkg-config: /home/linuxbrew/.linuxbrew/bin/pkg-config (0.29.2)` is interesting, as the system pkg-config should be located in `/usr/bin/pkg-config`.

Can you make sure that `/home/linuxbrew/.linuxbrew/bin/` is not in `$PATH`? It looks like your build-environment is finding the wrong binary.
You can check with `echo $PATH`. If neccessary, the ubuntu default can be temporary restored for the current shell with:
```console
$ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by Bearbobs** [comment]
Resolved it man.
Linux brew pkg-config was the main issue.

**Comment by Bearbobs** [comment]
sorry for the trouble.
Thanks btw.
