### ISSUE TITLE
Blur appears to overlay on top of the original

### ISSUE THREAD

**Issue by PixlOne** [tryone144/compton#33]
Platform: Arch Linux, Linux kernel 5.5.8

GPU, drivers, and screen setup: AMD Radeon RX 480, mesa 19.3.4-2, two 1920x1080 monitors configured side-by-side with xrandr

Compton version: picom wgit-e0149 (latest build from the feature/dual_kawase branch)

Compton configuration: https://pastebin.com/Rw2h1cHF

### Steps of reproduction

Launch picom with `--experimental-backends`, blur-background enabled, the blur method set to "dual_kawase", and the blur strength set to 5.0 or higher. This issue also occurs with box and gaussian methods and is visible with high enough strengths/deviations.

### Expected behavior

This should blur the background entirely, similar to [how it works with blur strength set to 2.0](https://i.imgur.com/lAKRuJU.png) but more intense.

### Current Behavior & Other details

The blur effect appears to overlay on top of the original background giving it a sort of "glowing" effect as shown [here](https://i.imgur.com/NHZZ1P6.png). As the blur strength increases, this glow effect becomes more apparent.

I've tested this on Openbox and XFCE and they both have this issue.

**Comment by tryone144** [comment]
This looks similar to #25. Please try changing line 67 in your config from
```
# blur-background-fixed = true;
```
to
```
blur-background-fixed = true;
```

You have set the window opacity manually with your `opacity-rule`s. If `blur-background-fixed` is **not** set to `true` (the default is `false`), the blurred background is only applied with the window's opacity leading to the observed "glow"-effect. This might be useful when (inactive) windows fade in and out to not leave a blurred frame when the window is close to fully transparent (see #2 for a more in-depth discussion). In all other cases you want to enable this option.

**Comment by PixlOne** [comment]
Thank you, that fixed it.
