### ISSUE TITLE
Please rebase feature/dual_kawase against yshui/picom#next

### ISSUE THREAD

**Issue by frebib** [tryone144/compton#36]
Some Arch users are relying on this package, which rebases your feature branch against upstream head before building. https://aur.archlinux.org/packages/picom-tryone-git/
Until recently this has been fine, but this change https://github.com/yshui/picom/commit/0fa0c352307f1a34f261419ce4a2f2a45a9ba85d is causing a merge conflict in the documentation.

If you'd rather not, I can open a PR to merge in upstream changes, but I think a rebase would be cleaner

**Comment by tryone144** [comment]
Will do. I hesitated to do this for every new upstream commit as quite a few have cloned this repo and a rebase requires force-pushing.

Thanks for the heads up.

**Comment by frebib** [comment]
Any update here? Are you planning on doing this soon or should I put a temporary measure in place as the package linked above currently does not build
Thanks

**Comment by tryone144** [comment]
Sorry for the delay. My dev-machine broke and I had to shuffle some parts around...

I've resolved the conflict and rebased `feature/dual_kawase` on top of `yshui:picom/next`.
BTW: Is there any particular reason for building picom in debug mode in the PKGBUILD?

**Comment by frebib** [comment]
Thank you! It's building cleanly again now 🎉

**Comment by frebib** [comment]
> Is there any particular reason for building picom in debug mode in the PKGBUILD?

Yes, because picom crashes frequently for me (when changing displays, dpi, etc), so this is hopefully to build in debug symbols to make stacktraces and coredumps usable. I'm not entirely sure if that's correct, though

**Comment by MyopicPaideia** [comment]
Trying to install - getting this error in the PKGBUILD
```
==> Starting prepare()...
fatal: remote yshui already exists.
==> ERROR: A failure occurred in prepare().
Aborting...

Command 'makepkg --force' failed to execute.
```
