### ISSUE TITLE
Screen is blacked if monitor is powered on/off

### ISSUE THREAD

**Issue by ghost** [tryone144/compton#37]
Platform: Void Linux x86_64
GPU, drivers, and screen setup: NVidia GTX 1050 with Displayport (if that helps)

Compton version: git head on branch feature/dual_kawase (commit 75dd1053cae2e1609e096b12943c6bef22b8a4a9)

Compton configuration: `--experimental-backends --backend glx --blur-background --blur-method dual_kawase --blur-strength 7`

### Steps of reproduction

1. clone the repo
2. git checkout feature/dual_kawase
3. build it
4. run it with 
5. turn off/unplug monitor
6. turn on monitor
[screen is black]
7. hit ctrl-c to kill picom
8. watch as the screen comes back

### Expected behavior

I can turn on and off my monitor and it will work

**Comment by tryone144** [comment]
Does the same happen with upstream https://github.com/yshui/picom and the experimental backends enabled? There seems to be some changes recently on how screen reconfiguration is handled that could have an impact on this issue.

**Comment by ghost** [comment]
It does, actually

**Comment by ghost** [comment]
closing this, it stopped happening
