### ISSUE TITLE
Blur strength not working in config file

### ISSUE THREAD

**Issue by rcarriga** [tryone144/compton#42]
Platform: Arch

Compton version: picom-tryone-git 1361_0.1_beta2.1012.gc67d7d7_2020.03.31-1 from AUR

Compton configuration: 
```
backend = "glx";
blur-method = "dual_kawase";
blur-strength = 1;
```

### Steps of reproduction

Run:
```bash
picom --experimental-backends
```

### Expected behavior

The blur strength is changed as specified in the config file.

### Current Behavior & Other details

The blur strength is the same as the default behaviour.

When the blur-strength line is removed and added to the command then it works as expected.

**Comment by tryone144** [comment]
Hey,
am I correct in assuming that [this](https://github.com/rcarriga/dotfiles/blob/7ee6dd2dc5cfb0668c0a2fdc3673904543354f4f/.config/picom.conf#L18) is your current picom config?
You have a typo in the config name: it's *blur_streng**t**h*, not *blur_strengh*. :wink: 

Let me know if that fixes your problem. Other than that, I can not reproduce the issue on my machine.

**Comment by rcarriga** [comment]
Haha well that's certainly embarrassing .... 
Thank you!

Also thanks for the work on this fork, it is really appreciated!
