### ISSUE TITLE
Neither directory contains a build file meson.build

### ISSUE THREAD

**Issue by hrqmonteiro** [tryone144/compton#47]
I'm trying to build, i clone and cd into directory but even with meson/ninja and all the dependencies installed, it gives me this error

**Comment by tryone144** [comment]
Hi, ~I think you forgot to put the actual error message in. :wink:~

Which branch are you using? I suggest using `feature/dual_kawase` as its the most recent and based on the current development version of picom. Check it out with `git checkout feature/dual_kawase`.
It's [readme](https://github.com/tryone144/compton/tree/feature/dual_kawase#to-build) includes the required commands to build:
```console
$ meson --buildtype=release . build
$ ninja -C build
```
The binary will be at `build/src/picom`, or you can install it with `ninja -C build install`.

Edit: Just seen, you put the error message in the title... :facepalm:

**Comment by tryone144** [comment]
@hrqmonteiro Did you manage to resolve the issue?
