### ISSUE TITLE
picom (with dual kawase blur) crashes whenever i try to close a window

### ISSUE THREAD

**Issue by lktoby** [tryone144/compton#48]
Platform:  arch linux xfce4, on a laptop

GPU, drivers, and screen setup:  nvidia geforce mx130

Picom version:  1417_Next.136.g7a3137b_2020.04.11-1 from [aur](https://aur.archlinux.org/packages/picom-tryone-git/)

Picom configuration:  https://pastebin.com/NfkB39wx

### Steps of reproduction

config path is in ~/.config/picom/picom.conf, try to run it on autostart for xfwm but it crashes whenever i try to close a window, command is picom --experimental-backends

### Expected behavior

will not crash and quit the program whenever i close a window (by clicking the x button on the upper right corner of the window)

### Current Behavior & Other details

when i try to run it on a terminal and try to close a window, this error message shows:
`[toby@tobyarch ~]$ picom --experimental-backends
[ 06/17/2020 00:12:41.739 win_clear_flags WARN ] Flags cleared on a destroyed window 0x00c0373f (Terminal - toby@tobyarch:~)
[ 06/17/2020 00:12:51.438 win_clear_flags WARN ] Flags cleared on a destroyed window 0x00c03a12 (Terminal - toby@tobyarch:~)
[ 06/17/2020 00:13:00.179 win_clear_flags WARN ] Flags cleared on a destroyed window 0x00c00c35 (#╭ミ★・general - Discord)
[ 06/17/2020 00:13:00.179 win_clear_flags WARN ] Flags cleared on a destroyed window 0x00c00c35 (#╭ミ★・general - Discord)
[ 06/17/2020 00:13:00.181 win_clear_flags WARN ] Flags cleared on a destroyed window 0x00c00c35 (#╭ミ★・general - Discord)
picom: ../src/backend/backend.c:270: paint_all_new: Assertion `!(w->flags & WIN_FLAGS_SHADOW_NONE)' failed.
Aborted (core dumped)
`
i tried to open a blank terminal screen and close it, it closes normally. try to run it with a command and exited, it closes normally. however when i try to close discord, it crashed and aborted the program

**Comment by abe1242** [comment]
I think this is supposed to go on https://github.com/sdhand/picom

**Comment by tryone144** [comment]
This issue is already known upstream with different "reasons" but all the same assertion failure.
See https://github.com/yshui/picom/issues/425, https://github.com/yshui/picom/issues/393, https://github.com/yshui/picom/issues/394, or https://github.com/yshui/picom/issues/396 for possible duplicates.

This should be tracked upstream, but I'll keep this issue open so others with the same problem can find the upstream tickets easier.

**Comment by peterge1998** [comment]
dual_kawase got [merged](https://github.com/yshui/picom/commit/731bd61467a5a004cc7f5f069fac11352d8f27dc) into [yshui/picom](https://github.com/yshui/picom) today, and picom-git from aur fixes the problem from this issue for me.

Thanks for all the work done @tryone144 <3
