### ISSUE TITLE
unable to build for MPR due to warnings treated as errors in makepkg & makedeb

### ISSUE THREAD

**Issue by justvipul** [tryone144/compton#54]
i am trying to include tryone144/compton into MPR(https://dur.hunterwittenborn.com/) and i have pkgbuild ready to deploy.
however the problem i am facing is that the build function in my pkgbuild get stopped due to warnings being treated as errors. more details are shown below.
1. here is my pkgbuild https://termbin.com/5nig
2. the problem is- while running the make command, the build() function is stopped as there are a bunch of warnings that pop up while running `make`, these warnings are treated as errors and the makepkg command stops the whole building process. 
https://termbin.com/ha8j<--- this is the error that happens
3. is it possible to rectify the code so as to remove the warnings in the build process?

**Comment by tryone144** [comment]
I have fixed the errors. The other warnings are a problem of compton itself and should not let the build process fail. Please try again.

Having said that, it seems as if compton isn't actively maintained anymore. [**picom**](https://github.com/yshui/picom) is a fork that tries to maintain and improve the old compton codebase and has superseeded compton in most distributions already. Picom also includes an improved implementation of the dual-filter kawase blur that will be part of the next regular release (most likely v9).

I'd personally rather improve picom with fixes and new features than maintain a separate (older) codebase. :wink:

**Comment by justvipul** [comment]
Thanks for the gesture and suggestion. I will check and confirm in some time.

**Comment by justvipul** [comment]
> I have fixed the errors. The other warnings are a problem of compton itself and should not let the build process fail. Please try again.
> 
> Having said that, it seems as if compton isn't actively maintained anymore. [**picom**](https://github.com/yshui/picom) is a fork that tries to maintain and improve the old compton codebase and has superseeded compton in most distributions already. Picom also includes an improved implementation of the dual-filter kawase blur that will be part of the next regular release (most likely v9).
> 
> I'd personally rather improve picom with fixes and new features than maintain a separate (older) codebase. 😉

Yes I just checked and everything works as it should. I know it's unmaintained but picom creates weird bugs in some use cases where if Compton used everything works perfectly. It works as it should and does the job pretty well. I use both compton-tryone-git and picom so I can relate with your thought. But having an option for the users is always better than suggesting our opinions. 
Btw is there any chance of such problems occurring again in the future with warnings treated as errors?

**Comment by tryone144** [comment]
> Btw is there any chance of such problems occurring again in the future with warnings treated as errors?

This depends on your compiler and flags set by the build system. the gcc/clang/… team might decide to introduce new warnings and change to treat warnings as errors. Most build systems set specific flags for hardening the executable which might include declaring (some) warnings as errors and might change at any time.

**Comment by justvipul** [comment]
Ok thanks for replying. I'm closing this issue. 
Compton-tryone-git is official now in mpr thanks to you👍
https://dur.hunterwittenborn.com/packages/compton-tryone-git/
