### ISSUE TITLE
Add the option to keep rendering a window, even if it is not visible or on the focused workspace

### ISSUE THREAD

**Issue by mvrozanti** [tryone144/compton#56]
Hi

I was looking into obs-studio and noticed that the captured window is gone if I alt-tab from it. At first I thought it was an OBS Studio thing but then I read [this issue on their repo](https://github.com/obsproject/obs-studio/issues/4160), that points out that is supposed to be a Xcompositor behavior. And I figured that behavior generally makes a lot of sense, no need to compute something that is not visible. Except in the case that you still want it captured by some video recording software, for example.

I have no idea of how viable or hard this would be, but I think that option would be a pretty neat addition. I wasn't sure whether to post this question on the upstream compton, but I thought I should just suggest this on the fork I use. 

What are your thoughts on it?

**Comment by mvrozanti** [comment]
Aaaand I just realized that also is not an Xcompositor issue. It's my window manager's.

**Comment by punmechanic** [comment]
Hey @mvrozanti, what WM were you using? Did you manage to solve this? I'm having a similar issue and finding the correct terms to even google this is proving challenging.

**Comment by mvrozanti** [comment]
Hi @trinitroglycerin  I'm on bspwm. I've managed to find a workaround that worked well enough for me, but it's really a hack:

Make the target window floating, resize it to your liking and move it off to the edge of the screen to the point that it is not visible to you but is still on the foreground. Then make the floating window sticky and there you go, you got a capture-capable window that's hidden from you, sort of. 

I believe this should or could eventually turn into a bspwm setting. I think this is the only way currently. I hope this helps
