### ISSUE TITLE
Can't make Kawase blur work 

### ISSUE THREAD

**Issue by tondorw** [tryone144/compton#6]
Hi tryone144, 

Thank you for the great work, to try out kawase blur on top of compton I am moved to your fork. This is no urgent matter, so please take your time.

Platform: Arch Linux with i3-gaps 
Terminal: Urxvt
Compton version: compton-tryone-git 0.1_beta2.95.g241bbc5-1 (built from AUR)
Compton configuration: https://pastebin.com/WNaDnCt0
.Xresources: https://pastebin.com/xgAqw81M

Kawase blur is not working with package installed. Tried to reinstall, no joy. At this stage I can only get the translucency work by changing the RGBA value.

**Comment by tryone144** [comment]
Hi,
You are using the `xrender` backend (line 53 in your compton.conf). The dual-kawase blur shader doesn't work with this backend.

Try changing it to the hardware accelerated `glx` backend. Then it should work.
